# Generated by Django 3.2.18 on 2023-04-23 11:45

from django.db import migrations

import authentication.models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", authentication.models.UserManager()),
            ],
        ),
    ]
